apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: stg

patches:
  - path: deployment-patch.yaml

images:
  - name: shekeriev/gitops-app
    newTag: latest