apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: gitops-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: app-cont
        image: shekeriev/gitops-app:latest
        ports:
        - containerPort: 80 
